package dpkg

import (
	"bufio"
	"os"
	"sort"
	"strings"
	"testing"
)

// Differential test against Debian's own apt_pkg.version_compare — the same C
// implementation dpkg and apt use. The hand-written table next door encodes
// what deb-version(7) says; this encodes what Debian actually does. The golden
// file is generated by testdata/gen_golden.py inside a Debian container and
// committed, so CI needs no Debian.
func loadGolden(t *testing.T) (ordered []string, equal [][2]string) {
	t.Helper()

	fh, err := os.Open("testdata/dpkg_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer fh.Close()

	section := ""
	scanner := bufio.NewScanner(fh)
	for scanner.Scan() {
		line := scanner.Text()
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if line == "SORTED" || line == "EQUAL" {
			section = line
			continue
		}
		switch section {
		case "SORTED":
			ordered = append(ordered, line)
		case "EQUAL":
			a, b, ok := strings.Cut(line, "\t")
			if !ok {
				t.Fatalf("malformed EQUAL line: %q", line)
			}
			equal = append(equal, [2]string{a, b})
		}
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("read golden: %v", err)
	}
	if len(ordered) == 0 {
		t.Fatal("golden file is empty — regenerate it")
	}
	return ordered, equal
}

func TestOrderingMatchesApt(t *testing.T) {
	want, _ := loadGolden(t)

	parsed := make([]Version, 0, len(want))
	for _, s := range want {
		v, err := Parse(s)
		if err != nil {
			t.Fatalf("Parse(%q) failed but apt accepted it: %v", s, err)
		}
		parsed = append(parsed, v)
	}

	// Shuffle deterministically first, so a stable sort cannot pass merely
	// because the input already arrived in order.
	for i := range parsed {
		j := (i * 7919) % len(parsed)
		parsed[i], parsed[j] = parsed[j], parsed[i]
	}
	sort.SliceStable(parsed, func(i, j int) bool { return Compare(parsed[i], parsed[j]) < 0 })

	for i, got := range parsed {
		// Compare parsed equality rather than strings: apt's total order places
		// equal-comparing versions arbitrarily relative to each other, and so
		// does ours.
		expected, err := Parse(want[i])
		if err != nil {
			t.Fatal(err)
		}
		if Compare(got, expected) != 0 {
			t.Fatalf("position %d: got %q, apt has %q", i, got, want[i])
		}
	}
	t.Logf("ordering agrees with apt across %d versions", len(want))
}

func TestEqualityMatchesApt(t *testing.T) {
	_, equal := loadGolden(t)

	for _, pair := range equal {
		a, err := Parse(pair[0])
		if err != nil {
			t.Fatalf("Parse(%q): %v", pair[0], err)
		}
		b, err := Parse(pair[1])
		if err != nil {
			t.Fatalf("Parse(%q): %v", pair[1], err)
		}
		if got := Compare(a, b); got != 0 {
			t.Errorf("Compare(%q, %q) = %d, apt says they are equal", pair[0], pair[1], got)
		}
	}
	t.Logf("agrees with apt on %d equality pairs", len(equal))
}
