package pep440

import (
	"bufio"
	"os"
	"sort"
	"strings"
	"testing"
)

// Differential test against CPython's own packaging library.
//
// The hand-written table next door encodes what the spec says; this encodes
// what the reference implementation actually does across ~9.6k versions. A
// hand-written parser is only trustworthy if it agrees with the thing every
// Python tool already uses. The golden file is generated by
// testdata/gen_golden.py and committed so CI needs no Python.
func loadGolden(t *testing.T) (normalize [][2]string, sorted []string) {
	t.Helper()

	fh, err := os.Open("testdata/packaging_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer fh.Close()

	section := ""
	scanner := bufio.NewScanner(fh)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)

	for scanner.Scan() {
		line := scanner.Text()
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if line == "NORMALIZE" || line == "SORTED" {
			section = line
			continue
		}
		switch section {
		case "NORMALIZE":
			raw, norm, ok := strings.Cut(line, "\t")
			if !ok {
				t.Fatalf("malformed NORMALIZE line: %q", line)
			}
			normalize = append(normalize, [2]string{raw, norm})
		case "SORTED":
			sorted = append(sorted, line)
		}
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("read golden: %v", err)
	}
	if len(normalize) == 0 || len(sorted) == 0 {
		t.Fatal("golden file is empty — regenerate it")
	}
	return normalize, sorted
}

func TestNormalizationMatchesPackaging(t *testing.T) {
	normalize, _ := loadGolden(t)

	failures := 0
	for _, pair := range normalize {
		raw, want := pair[0], pair[1]

		v, err := Parse(raw)
		if err != nil {
			t.Errorf("Parse(%q) failed but packaging accepted it: %v", raw, err)
			if failures++; failures > 20 {
				t.Fatal("too many failures")
			}
			continue
		}
		if got := v.String(); got != want {
			t.Errorf("Parse(%q).String() = %q, packaging says %q", raw, got, want)
			if failures++; failures > 20 {
				t.Fatal("too many failures")
			}
		}
	}
	t.Logf("checked %d versions against packaging", len(normalize))
}

func TestOrderingMatchesPackaging(t *testing.T) {
	_, want := loadGolden(t)

	parsed := make([]Version, 0, len(want))
	for _, s := range want {
		v, err := Parse(s)
		if err != nil {
			t.Fatalf("Parse(%q): %v", s, err)
		}
		parsed = append(parsed, v)
	}

	// Shuffle deterministically before sorting, so a stable sort cannot pass by
	// virtue of the input already being in order.
	for i := range parsed {
		j := (i * 7919) % len(parsed)
		parsed[i], parsed[j] = parsed[j], parsed[i]
	}

	sort.SliceStable(parsed, func(i, j int) bool { return Compare(parsed[i], parsed[j]) < 0 })

	for i, v := range parsed {
		// Compare on parsed equality, not strings: packaging's total order puts
		// equal-comparing versions in an arbitrary relative position, and so do we.
		expected, err := Parse(want[i])
		if err != nil {
			t.Fatal(err)
		}
		if Compare(v, expected) != 0 {
			t.Fatalf("position %d: got %q, packaging has %q", i, v, want[i])
		}
	}
	t.Logf("ordering agrees with packaging across %d versions", len(want))
}
